# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/MhomMD/md/git-md/vergifac3/master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/MhomMD/md/git-md/vergifac3/master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/MhomMD/md/git-md/vergifac3/master/CMakeFiles /home/MhomMD/md/git-md/vergifac3/master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/MhomMD/md/git-md/vergifac3/master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vergifac

# Build rule for target.
vergifac: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vergifac
.PHONY : vergifac

# fast build rule for target.
vergifac/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/build
.PHONY : vergifac/fast

src/editfast.o: src/editfast.c.o
.PHONY : src/editfast.o

# target to build an object file
src/editfast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/editfast.c.o
.PHONY : src/editfast.c.o

src/editfast.i: src/editfast.c.i
.PHONY : src/editfast.i

# target to preprocess a source file
src/editfast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/editfast.c.i
.PHONY : src/editfast.c.i

src/editfast.s: src/editfast.c.s
.PHONY : src/editfast.s

# target to generate assembly for a file
src/editfast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/editfast.c.s
.PHONY : src/editfast.c.s

src/fastmenu.o: src/fastmenu.c.o
.PHONY : src/fastmenu.o

# target to build an object file
src/fastmenu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/fastmenu.c.o
.PHONY : src/fastmenu.c.o

src/fastmenu.i: src/fastmenu.c.i
.PHONY : src/fastmenu.i

# target to preprocess a source file
src/fastmenu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/fastmenu.c.i
.PHONY : src/fastmenu.c.i

src/fastmenu.s: src/fastmenu.c.s
.PHONY : src/fastmenu.s

# target to generate assembly for a file
src/fastmenu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/fastmenu.c.s
.PHONY : src/fastmenu.c.s

src/listcli.o: src/listcli.c.o
.PHONY : src/listcli.o

# target to build an object file
src/listcli.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/listcli.c.o
.PHONY : src/listcli.c.o

src/listcli.i: src/listcli.c.i
.PHONY : src/listcli.i

# target to preprocess a source file
src/listcli.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/listcli.c.i
.PHONY : src/listcli.c.i

src/listcli.s: src/listcli.c.s
.PHONY : src/listcli.s

# target to generate assembly for a file
src/listcli.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/listcli.c.s
.PHONY : src/listcli.c.s

src/listprod.o: src/listprod.c.o
.PHONY : src/listprod.o

# target to build an object file
src/listprod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/listprod.c.o
.PHONY : src/listprod.c.o

src/listprod.i: src/listprod.c.i
.PHONY : src/listprod.i

# target to preprocess a source file
src/listprod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/listprod.c.i
.PHONY : src/listprod.c.i

src/listprod.s: src/listprod.c.s
.PHONY : src/listprod.s

# target to generate assembly for a file
src/listprod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/listprod.c.s
.PHONY : src/listprod.c.s

src/memodoc.o: src/memodoc.c.o
.PHONY : src/memodoc.o

# target to build an object file
src/memodoc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/memodoc.c.o
.PHONY : src/memodoc.c.o

src/memodoc.i: src/memodoc.c.i
.PHONY : src/memodoc.i

# target to preprocess a source file
src/memodoc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/memodoc.c.i
.PHONY : src/memodoc.c.i

src/memodoc.s: src/memodoc.c.s
.PHONY : src/memodoc.s

# target to generate assembly for a file
src/memodoc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/memodoc.c.s
.PHONY : src/memodoc.c.s

src/mesfast.o: src/mesfast.c.o
.PHONY : src/mesfast.o

# target to build an object file
src/mesfast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/mesfast.c.o
.PHONY : src/mesfast.c.o

src/mesfast.i: src/mesfast.c.i
.PHONY : src/mesfast.i

# target to preprocess a source file
src/mesfast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/mesfast.c.i
.PHONY : src/mesfast.c.i

src/mesfast.s: src/mesfast.c.s
.PHONY : src/mesfast.s

# target to generate assembly for a file
src/mesfast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/mesfast.c.s
.PHONY : src/mesfast.c.s

src/paramsfac.o: src/paramsfac.c.o
.PHONY : src/paramsfac.o

# target to build an object file
src/paramsfac.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/paramsfac.c.o
.PHONY : src/paramsfac.c.o

src/paramsfac.i: src/paramsfac.c.i
.PHONY : src/paramsfac.i

# target to preprocess a source file
src/paramsfac.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/paramsfac.c.i
.PHONY : src/paramsfac.c.i

src/paramsfac.s: src/paramsfac.c.s
.PHONY : src/paramsfac.s

# target to generate assembly for a file
src/paramsfac.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/paramsfac.c.s
.PHONY : src/paramsfac.c.s

src/saifac.o: src/saifac.c.o
.PHONY : src/saifac.o

# target to build an object file
src/saifac.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saifac.c.o
.PHONY : src/saifac.c.o

src/saifac.i: src/saifac.c.i
.PHONY : src/saifac.i

# target to preprocess a source file
src/saifac.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saifac.c.i
.PHONY : src/saifac.c.i

src/saifac.s: src/saifac.c.s
.PHONY : src/saifac.s

# target to generate assembly for a file
src/saifac.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saifac.c.s
.PHONY : src/saifac.c.s

src/saifaccod.o: src/saifaccod.c.o
.PHONY : src/saifaccod.o

# target to build an object file
src/saifaccod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saifaccod.c.o
.PHONY : src/saifaccod.c.o

src/saifaccod.i: src/saifaccod.c.i
.PHONY : src/saifaccod.i

# target to preprocess a source file
src/saifaccod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saifaccod.c.i
.PHONY : src/saifaccod.c.i

src/saifaccod.s: src/saifaccod.c.s
.PHONY : src/saifaccod.s

# target to generate assembly for a file
src/saifaccod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saifaccod.c.s
.PHONY : src/saifaccod.c.s

src/saiprod.o: src/saiprod.c.o
.PHONY : src/saiprod.o

# target to build an object file
src/saiprod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saiprod.c.o
.PHONY : src/saiprod.c.o

src/saiprod.i: src/saiprod.c.i
.PHONY : src/saiprod.i

# target to preprocess a source file
src/saiprod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saiprod.c.i
.PHONY : src/saiprod.c.i

src/saiprod.s: src/saiprod.c.s
.PHONY : src/saiprod.s

# target to generate assembly for a file
src/saiprod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saiprod.c.s
.PHONY : src/saiprod.c.s

src/saiscli.o: src/saiscli.c.o
.PHONY : src/saiscli.o

# target to build an object file
src/saiscli.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saiscli.c.o
.PHONY : src/saiscli.c.o

src/saiscli.i: src/saiscli.c.i
.PHONY : src/saiscli.i

# target to preprocess a source file
src/saiscli.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saiscli.c.i
.PHONY : src/saiscli.c.i

src/saiscli.s: src/saiscli.c.s
.PHONY : src/saiscli.s

# target to generate assembly for a file
src/saiscli.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/saiscli.c.s
.PHONY : src/saiscli.c.s

src/sqlcliDB.o: src/sqlcliDB.c.o
.PHONY : src/sqlcliDB.o

# target to build an object file
src/sqlcliDB.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/sqlcliDB.c.o
.PHONY : src/sqlcliDB.c.o

src/sqlcliDB.i: src/sqlcliDB.c.i
.PHONY : src/sqlcliDB.i

# target to preprocess a source file
src/sqlcliDB.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/sqlcliDB.c.i
.PHONY : src/sqlcliDB.c.i

src/sqlcliDB.s: src/sqlcliDB.c.s
.PHONY : src/sqlcliDB.s

# target to generate assembly for a file
src/sqlcliDB.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/src/sqlcliDB.c.s
.PHONY : src/sqlcliDB.c.s

util/gencbox.o: util/gencbox.c.o
.PHONY : util/gencbox.o

# target to build an object file
util/gencbox.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/gencbox.c.o
.PHONY : util/gencbox.c.o

util/gencbox.i: util/gencbox.c.i
.PHONY : util/gencbox.i

# target to preprocess a source file
util/gencbox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/gencbox.c.i
.PHONY : util/gencbox.c.i

util/gencbox.s: util/gencbox.c.s
.PHONY : util/gencbox.s

# target to generate assembly for a file
util/gencbox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/gencbox.c.s
.PHONY : util/gencbox.c.s

util/genctrl.o: util/genctrl.c.o
.PHONY : util/genctrl.o

# target to build an object file
util/genctrl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/genctrl.c.o
.PHONY : util/genctrl.c.o

util/genctrl.i: util/genctrl.c.i
.PHONY : util/genctrl.i

# target to preprocess a source file
util/genctrl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/genctrl.c.i
.PHONY : util/genctrl.c.i

util/genctrl.s: util/genctrl.c.s
.PHONY : util/genctrl.s

# target to generate assembly for a file
util/genctrl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/genctrl.c.s
.PHONY : util/genctrl.c.s

util/genfq.o: util/genfq.c.o
.PHONY : util/genfq.o

# target to build an object file
util/genfq.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/genfq.c.o
.PHONY : util/genfq.c.o

util/genfq.i: util/genfq.c.i
.PHONY : util/genfq.i

# target to preprocess a source file
util/genfq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/genfq.c.i
.PHONY : util/genfq.c.i

util/genfq.s: util/genfq.c.s
.PHONY : util/genfq.s

# target to generate assembly for a file
util/genfq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/genfq.c.s
.PHONY : util/genfq.c.s

util/genftablo.o: util/genftablo.c.o
.PHONY : util/genftablo.o

# target to build an object file
util/genftablo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/genftablo.c.o
.PHONY : util/genftablo.c.o

util/genftablo.i: util/genftablo.c.i
.PHONY : util/genftablo.i

# target to preprocess a source file
util/genftablo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/genftablo.c.i
.PHONY : util/genftablo.c.i

util/genftablo.s: util/genftablo.c.s
.PHONY : util/genftablo.s

# target to generate assembly for a file
util/genftablo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vergifac.dir/build.make CMakeFiles/vergifac.dir/util/genftablo.c.s
.PHONY : util/genftablo.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vergifac"
	@echo "... src/editfast.o"
	@echo "... src/editfast.i"
	@echo "... src/editfast.s"
	@echo "... src/fastmenu.o"
	@echo "... src/fastmenu.i"
	@echo "... src/fastmenu.s"
	@echo "... src/listcli.o"
	@echo "... src/listcli.i"
	@echo "... src/listcli.s"
	@echo "... src/listprod.o"
	@echo "... src/listprod.i"
	@echo "... src/listprod.s"
	@echo "... src/memodoc.o"
	@echo "... src/memodoc.i"
	@echo "... src/memodoc.s"
	@echo "... src/mesfast.o"
	@echo "... src/mesfast.i"
	@echo "... src/mesfast.s"
	@echo "... src/paramsfac.o"
	@echo "... src/paramsfac.i"
	@echo "... src/paramsfac.s"
	@echo "... src/saifac.o"
	@echo "... src/saifac.i"
	@echo "... src/saifac.s"
	@echo "... src/saifaccod.o"
	@echo "... src/saifaccod.i"
	@echo "... src/saifaccod.s"
	@echo "... src/saiprod.o"
	@echo "... src/saiprod.i"
	@echo "... src/saiprod.s"
	@echo "... src/saiscli.o"
	@echo "... src/saiscli.i"
	@echo "... src/saiscli.s"
	@echo "... src/sqlcliDB.o"
	@echo "... src/sqlcliDB.i"
	@echo "... src/sqlcliDB.s"
	@echo "... util/gencbox.o"
	@echo "... util/gencbox.i"
	@echo "... util/gencbox.s"
	@echo "... util/genctrl.o"
	@echo "... util/genctrl.i"
	@echo "... util/genctrl.s"
	@echo "... util/genfq.o"
	@echo "... util/genfq.i"
	@echo "... util/genfq.s"
	@echo "... util/genftablo.o"
	@echo "... util/genftablo.i"
	@echo "... util/genftablo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

